import { Model } from 'mongoose';
import { Transaction, TransactionDocument } from '../entities/transaction.entity';
import { LoyaltyschemeDocument } from '../entities/loyaltyscheme.entity';
import { CouponDocument } from '../entities/coupon.entity';
import { CustomerDocument } from '../entities/customer.entity';
import { ProductDocument } from '../entities/product.entity';
import { SettingProjectDocument } from '../entities/setting.project.entity';
import { CreateTransactionDto, ProductDropdownDto, StatusCouponDtos, StatusTransactionDto, UpdateTransactionDto } from '../user/transactions/dto/request-transaction.dto';
import { AddInvalidCouponDTO, AdminCouponsScanDTO, FilterPaginationInvalidCouponDto, FilterPaginationTransactionDto, ImportCouponTransactionDTO, ImportTransactionDTO } from '../dto/transaction.dto';
import { GetTransactionInfoDto } from '../user/transactions/dto/response-transaction.dto';
import { Request } from 'express';
import { InvalidCouponDocument } from 'src/entities/invalidcoupon.entity';
import { CouponProfileDocument } from 'src/entities/couponprofile.entity';
import { CustomerIdDTO } from 'src/dto/dashboard-dto';
export declare class TransactionsService {
    private transactionModel;
    private productModel;
    private schemeModel;
    private couponModel;
    private customerModel;
    private projectSettingModel;
    private invalidCouponModel;
    private couponProfileModel;
    constructor(transactionModel: Model<TransactionDocument>, productModel: Model<ProductDocument>, schemeModel: Model<LoyaltyschemeDocument>, couponModel: Model<CouponDocument>, customerModel: Model<CustomerDocument>, projectSettingModel: Model<SettingProjectDocument>, invalidCouponModel: Model<InvalidCouponDocument>, couponProfileModel: Model<CouponProfileDocument>);
    createTransaction(createTransactionDto: CreateTransactionDto, req: Request): Promise<GetTransactionInfoDto>;
    getAllTransaction(paginationDto: FilterPaginationTransactionDto): Promise<any>;
    getTransactionInfo(id: string): Promise<GetTransactionInfoDto>;
    updateTransactionInfo(id: string, updateTransactionDto: UpdateTransactionDto): Promise<Transaction>;
    deleteTransaction(id: string): Promise<Transaction>;
    updateStatus(statusTransactionDto: StatusTransactionDto): Promise<Transaction>;
    private handleTransactions;
    couponScans(couponsScanDTO: AdminCouponsScanDTO, req?: Request): Promise<any>;
    getActiveSchemes(): Promise<any>;
    getScanedCoupons(toscaned: any): Promise<any>;
    getCouponsToScans(toscaned: any): Promise<any>;
    getScanSchemeDetail(getdate: any, customerid: string): Promise<any>;
    getSchemeDetailByProduct(schemeid: any, products: any): Promise<any>;
    getCustomerProfileInfo(customerid: any): Promise<any>;
    leaderboard(req: any): Promise<any>;
    welcomePoints(customerid: any): Promise<any>;
    getAllCustomerTransaction(startDate: string, endDate: string, customerIdDTO: CustomerIdDTO): Promise<any>;
    getNewRefNoTransaction(): Promise<number>;
    importScanTransactions(createTransactionDto: ImportCouponTransactionDTO[]): Promise<any>;
    checkCouponValidation(coupon: string): Promise<any>;
    checkCouponScanedBefore(coupon: string): Promise<any>;
    importTransactions(createTransactionDto: ImportTransactionDTO[]): Promise<any>;
    addInvalidCoupon(addInvalidCouponDTO: AddInvalidCouponDTO): Promise<any>;
    getAllInvalidCoupon(paginationDto: FilterPaginationInvalidCouponDto): Promise<any>;
    productDropdown(statusCouponDto: ProductDropdownDto): Promise<any>;
    updateCouponStatus(req: Request, statusCouponDto: StatusCouponDtos): Promise<any>;
    getAllCustomerInvalidCoupon(customerIdDTO: CustomerIdDTO): Promise<any>;
    couponScansByAdmin(req: Request, addInvalidCouponDTO: AddInvalidCouponDTO): Promise<any>;
    test(): Promise<void>;
}
